#!/bin/bash
# programming constructs—primarily if statements and case structures
# Comparisons like -gt, -lt, -eq
# Common mistakes:
# using == for numbers

# Troubleshooting:
# - Use correct operator
# DEMO
a=5
b=10
if [ $a -lt $b ]
then
    echo "a is less than b"
fi